### ISSUE TITLE
turbo - doesnt work

### ISSUE THREAD

**Issue by bigmisha87** [Stability-AI/sd3.5#1]
![Screenshot (13)](https://github.com/user-attachments/assets/fe02f4c4-0807-4601-9d9f-b6c49a45a04a)
![Screenshot (14)](https://github.com/user-attachments/assets/630a1906-f2af-47f8-bc67-a232deeb49e8)

i downloaded the Text Encoders：

CLIPs: [OpenCLIP-ViT/G](https://github.com/mlfoundations/open_clip), [CLIP-ViT/L](https://github.com/openai/CLIP/tree/main), context length 77 tokens
T5: [T5-xxl](https://huggingface.co/google/t5-v1_1-xxl), context length 77/256 tokens at different stages of training

and the checkpoint model.
but it doesnt work.

i have a 3090rtx.

FLUX works
and many other SDXL models work fine.

**Comment by brianfitzgerald** [comment]
It looks like you're using Automatic1111's stable-diffusion-3.5, which doesn't use this repository. A1111 doesn't support 3.5 at the moment but will likely support it soon. I'd keep a tab on [their issues page](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues) to see when they'll support it.
