### ISSUE TITLE
img2img results pixelated and low quality

### ISSUE THREAD

**Issue by reesekneeland** [Stability-AI/sd3.5#6]
Hello, when using the sd3_infer.py file in its default configuration, any image I upload as init_image, and any denoise value I choose below 1 results in very pixelated outputs, attached is an example of an initial image (left) and the output I get from using a simple prompt ("a horse") with denoise=0.6. This is using a fresh python 3.11 environment with the requirements installed. 

One thing I noticed is that the T5 model file the code expects is t5xxl.safetensors (which loads as dtype float32), and the one linked in the readme is t5xxl_fp16.safetensors. I don't think this is related as the img2img issue only happens when an init_image is provided, and doesn't have anything to do with the t5 embedding, but you may want to also ensure the t5 model files match as intended.

![image](https://github.com/user-attachments/assets/b84ba225-4ed3-4c4b-8e76-22871894ae93)
![image](https://github.com/user-attachments/assets/cae63024-4f15-472f-8b64-3d06df1ab7f1)

**Comment by reesekneeland** [comment]
Heres another example, denoise=0.6, prompt="a woman in a field"

![image](https://github.com/user-attachments/assets/2b88c4bb-62f6-4c7a-a874-6c0036fc8ad4)
![image](https://github.com/user-attachments/assets/59bfb871-1670-4b46-aefc-e939826b4931)

**Comment by SoonNOON** [comment]
Yes, I encountered the same problem.

**Comment by dan4ik94** [comment]
better wait for finetunes, maybe this will be fixed. What I discovered is I get better results with denoised images

**Comment by winterfell00** [comment]
> Try "euler" sampler (default for medium is "dpmpp_2m"). It works for me.

Hi, Could you please provide more details on how you implemented it? If possible, could you share a snippet of your code or any specific settings you used? Thank you!

**Comment by magorokhoov** [comment]
> > Try "euler" sampler (default for medium is "dpmpp_2m"). It works for me.
> 
> Hi, Could you please provide more details on how you implemented it? If possible, could you share a snippet of your code or any specific settings you used? Thank you!

This repo has already implemented euler sampler. Just need to use it.
Here is the example of my script (just copy paste):
```sh
python sd3_infer.py --prompt prompt_v4.txt --init_image "000000.png" --model models/sd3.5_medium.safetensors --denoise 0.3 --steps 20 --width 1024 --height 1520 --sampler euler
```

So you add this:
```sh
python sd3_infer.py --sampler euler
```

**Comment by magorokhoov** [comment]
> I'll give it a try. Thanks a lot for your help!

Good luck! If you need SD3.5 non-automaticaly without code but still locally - you also can use ComfyUI.
